### ISSUE TITLE
Show soil type in the background of the fibre chart with the same colors as the section

### ISSUE THREAD

**Issue by dharezlak** [ismop/eitwid#95]

**Comment by mkasztelnik** [comment]
@nowakowski would it be possible to add cable distance interval for `Section` resource in REST API?

**Comment by nowakowski** [comment]
Please be more specific. Which of the following are you interested in:

- filtering Sections by cable distance interval
- embedding cable distance information (from/to) in each `Section` object returned by the API

Regardless, this is super ugly because cable distance is not a property of `Section`; we're creating an API that is specifically dedicated to the experimental levee in Czernichów.

**Comment by mkasztelnik** [comment]
You are right. I will try to calculate start and end section manually in the fiber view, if I will fail than I will ask about second option you described.

**Comment by nowakowski** [comment]
Roger that.
